### ISSUE TITLE
Copy empty directories?

### ISSUE THREAD

**Issue by marknguy** [aws-samples/snowball-uploader#1]
Does this script copy empty directories?  The S3 interface doesn't, but hoping this script will.  Please advise.  Great Job!

**Comment by kyongki** [comment]
I haven't tried.. but I think that it wouldn't copy empty directories if there are no objects.
I'll test it and let you know

**Comment by marknguy** [comment]
When I did the genlist, the empty directories were not listed.  So it may not work.  Would be nice to have this ability since aws s3 cp and aws s3 sync do not copy empty directories either.

**Comment by kyongki** [comment]
Thanks marknguy for testing it.
Even though snowball_uploader can archive empty directories, if s3 does not support empty ones, changing the script is useless. The directory is a part of key(file name) in S3, in contrary the directory is one of file in traditional filesystem. Therefore, directory itself can be exist alone is S3.
I'm sorry that I can't help you.

**Comment by marknguy** [comment]
s3 supports empty directories/folders.  You can create one in the console.  Or you can do it programmatically.  Something like s3.put_object(Bucket=bucket_name, Key=(empty-folder-name+’/’))

**Comment by kyongki** [comment]
You're right and early my mention was wrong. Thanks for correcting me.
I'll do some changes to support empty directory, but it needs time.
please wait for some time..
