### ISSUE TITLE
Issues running on Windows

### ISSUE THREAD

**Issue by nomidd** [aws-samples/snowball-uploader#4]
Running on Windows 10, there is a scoping issue with the s3 object that produces the error below. 
    mpu = s3.create_multipart_upload(Bucket=bucket_name, Key=key_name, StorageClass=s3_class, Metadata={"snowball-auto-extract": "true"})
NameError: name 's3' is not defined

Moving the following lines of code to the global part of the file resolved it:
session = boto3.Session(profile_name=profile_name)
s3 = session.client('s3', endpoint_url=endpoint)

Additionally, an error occurred with the specific file name below.  It seems likely to be due to the comma in the file name.
File Name in the file list is correct:
/Users/XXXXXXXX/Downloads\Get started with AWS networking- Set up, secure, and monitor global networks.pptx, 8510080, 1660587266.6938798
Error during copy:
/Users/XXXXXXXX/Downloads\Get started with AWS networking- Set up is not exist...............................................

**Comment by kyongki** [comment]
Thanks for issuing variable scope error... I'll change it.
for the 'file name with comma', you can resolve it replacing delimiter from ',  ' to any other character which not included in file name, for example '|'.  Default delimiter is ', ' , so those filename with 'comma and space' would be cause error.
